### ISSUE TITLE
Please update npm package :-)

### ISSUE THREAD

**Issue by ecdlguy** [danielbayerlein/vallox-api#19]
Hi,
thanks again for merging my request!
I'm using the npm package in node red for collecting metrics from my Vallox unit.
Could you please update on npm?
cheers, Thorsten

**Comment by danielbayerlein** [comment]
Done, see https://github.com/danielbayerlein/vallox-api/releases/tag/v1.0.0 🙂

**Comment by ecdlguy** [comment]
Thank you!  :+1:
